name: Production Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

#env:
#WEB_APP_API: ${{ secrets.WEB_APP_API }}
#WEB_APP_FILES: ${{ secrets.WEB_APP_FILES }}

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Install
        run: npm install
      - name: NPM Build
        run: npm run build
        env:
          CI: false # Without this, will fail on any web app build warnings!!!

      - name: Deploy to S3 without index.html on DEV
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete --exclude 'index.html'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'dist'

      - name: Deploy index to S3 on DEV
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete --include 'index.html'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'dist'
